from utils.consts import MODELS_DIR, CONFIG_DIR

VISION_BASE_DIR = "vision"

VISION_MODELS_DIR = f"{VISION_BASE_DIR}/{MODELS_DIR}"
VISION_CONFIG_DIR = f"{VISION_BASE_DIR}/{CONFIG_DIR}"

MODULE_MODELS_DIR = VISION_MODELS_DIR
MODULE_CONFIG_DIR = VISION_CONFIG_DIR
